name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza 'main' con el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: Deploy
        uses: actions/deploy-pages@v1
